/*
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
*/

// src/app/layout.tsx
import type { Metadata } from 'next'; // Importe Metadata do next
import { Inter } from 'next/font/google'; // Ou sua fonte configurada
import './globals.css';
import Navbar from '@/components/Navbar'; // Importa o componente Navbar
// import Footer from '@/components/Footer'; // Importa o componente Footer

const inter = Inter({ subsets: ['latin'] }); // Ou sua fonte configurada

// Adicione a exportação de metadata aqui
export const metadata: Metadata = {
  title: 'Associação Espaço Curumim', // Título para esta página ou aplicação
  description: 'Histórias inspiradoras, notícias e reflexões sobre o trabalho da Associação Espaço Curumim.', // Adicione uma descrição
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">      
      <body className={inter.className} suppressHydrationWarning={true}>
        <Navbar /> 
          {children}
        { /* <Footer /> */}
      </body>   
    </html>
  );
}